## Introduction : Transformers

### Modeles

Hugging Face : GPT2

### Evaluation

- BLEU/ROUGE Score
- BERT Score

### Bechmark

| Modèle                                | BLEU Score | ROUGE-L Score | BERTScore |
|---------------------------------------|------------|----------------|-----------|
| **GPT-2**          | 0.0115     | 0.0952         | 0.8339    |
| **GPT-2 AventIQ**                     | 0.0047     | 0.1063         | 0.8294    |
| **DistilGPT2 yroshan**                     | 0.0033     | 0.0972         |  0.8278    |

## Common code

In [1]:

import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import re

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-05-07 17:26:59.492893: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1746631619.664382   10341 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1746631619.713360   10341 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1746631620.097944   10341 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746631620.097983   10341 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746631620.097985   10341 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746631620.097987   10341 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-07 17:27:00.133833: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# Load dataset and preprocess
df = pd.read_csv("MovieDataThread.csv")
df = df.dropna(subset=["Script"])
df = df.sample(n=1000, random_state=42)

In [3]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
train_texts, test_texts = train_test_split(df["Script"].tolist(), test_size=0.2, random_state=42)
dataset = DatasetDict({
    "train": Dataset.from_dict({"Script": train_texts}),
    "test": Dataset.from_dict({"Script": test_texts})
})

## Hugging face Transformer (GPT2)

https://huggingface.co/openai-community/gpt2

### Model

In [8]:
# Load the tokenizer and model from Hugging Face (GPT2)
model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained(model_name)

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [9]:
# Tokenize the dataset
def tokenize_function(example):
    encoding = tokenizer(example["Script"], truncation=True, padding="longest", max_length=256)
    encoding["labels"] = encoding["input_ids"].copy()
    return encoding

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["Script"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

Map: 100%|██████████| 800/800 [00:32<00:00, 24.30 examples/s]
Map: 100%|██████████| 200/200 [00:08<00:00, 22.32 examples/s]

### Train

In [ ]:
# Train the model (Arguments)
training_args = TrainingArguments(
    output_dir="./gpt2-script",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    weight_decay=0.01,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=5,
    logging_dir="./logs",
    save_strategy="no",
    fp16=False,
    lr_scheduler_type="linear",
    warmup_steps=100,
)

In [11]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

In [12]:
# Train the model
trainer.train()

# Save the model
trainer.save_model("./gpt2-script")

### Load model

In [16]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import evaluate

# Load the model for evaluation
model = GPT2LMHeadModel.from_pretrained("./gpt2-script")
tokenizer = GPT2Tokenizer.from_pretrained("./gpt2-script")

# Generate text
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")

def generate_text(prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

### Evaluation

In [18]:
bleu_scores = []
rouge_scores = []
bert_scores = []

PROMPT_LENGTH = 200
GENERATION_MAX_LENGTH = 100

total = len(test_texts)
i = 1

print("Evaluating the model on the test set...")
for full_text in test_texts:
    print(f"Evaluating {i}/{total}...")
    prompt = full_text[:PROMPT_LENGTH]
    reference = full_text[PROMPT_LENGTH:PROMPT_LENGTH + GENERATION_MAX_LENGTH]

    generated = generate_text(prompt, max_new_tokens=GENERATION_MAX_LENGTH)
    generated = generated[PROMPT_LENGTH:PROMPT_LENGTH + GENERATION_MAX_LENGTH]

    # BLEU
    bleu_result = bleu.compute(predictions=[generated], references=[[reference]])
    bleu_scores.append(bleu_result["bleu"])

    # ROUGE
    rouge_result = rouge.compute(predictions=[generated], references=[reference])
    rouge_scores.append(rouge_result["rougeL"])

    # BERTScore
    bert_result = bertscore.compute(predictions=[generated], references=[reference], lang="en")
    bert_scores.append(bert_result["f1"][0])

    i += 1

print(f"Average BLEU score : {sum(bleu_scores) / len(bleu_scores):.6f}")
print(f"Average ROUGE score : {sum(rouge_scores) / len(rouge_scores):.6f}")
print(f"Average BERT score : {sum(bert_scores) / len(bert_scores):.6f}")

Evaluating the model on the test set...
Evaluating 1/200...
Evaluating 2/200...
Evaluating 3/200...
Evaluating 4/200...
Evaluating 5/200...
Evaluating 6/200...
Evaluating 7/200...
Evaluating 8/200...
Evaluating 9/200...
Evaluating 10/200...
Evaluating 11/200...
Evaluating 12/200...
Evaluating 13/200...
Evaluating 14/200...
Evaluating 15/200...
Evaluating 16/200...
Evaluating 17/200...
Evaluating 18/200...
Evaluating 19/200...
Evaluating 20/200...
Evaluating 21/200...
Evaluating 22/200...
Evaluating 23/200...
Evaluating 24/200...
Evaluating 25/200...
Evaluating 26/200...
Evaluating 27/200...
Evaluating 28/200...
Evaluating 29/200...
Evaluating 30/200...
Evaluating 31/200...
Evaluating 32/200...
Evaluating 33/200...
Evaluating 34/200...
Evaluating 35/200...
Evaluating 36/200...
Evaluating 37/200...
Evaluating 38/200...
Evaluating 39/200...
Evaluating 40/200...
Evaluating 41/200...
Evaluating 42/200...
Evaluating 43/200...
Evaluating 44/200...
Evaluating 45/200...
Evaluating 46/200...
Evaluating 47/200...
Evaluating 48/200...
Evaluating 49/200...
Evaluating 50/200...
Evaluating 51/200...
Evaluating 52/200...
Evaluating 53/200...
Evaluating 54/200...
Evaluating 55/200...
Evaluating 56/200...
Evaluating 57/200...
Evaluating 58/200...
Evaluating 59/200...
Evaluating 60/200...
Evaluating 61/200...
Evaluating 62/200...
Evaluating 63/200...
Evaluating 64/200...
Evaluating 65/200...
Evaluating 66/200...
Evaluating 67/200...
Evaluating 68/200...
Evaluating 69/200...
Evaluating 70/200...
Evaluating 71/200...
Evaluating 72/200...
Evaluating 73/200...
Evaluating 74/200...
Evaluating 75/200...
Evaluating 76/200...
Evaluating 77/200...
Evaluating 78/200...
Evaluating 79/200...
Evaluating 80/200...
Evaluating 81/200...
Evaluating 82/200...
Evaluating 83/200...
Evaluating 84/200...
Evaluating 85/200...
Evaluating 86/200...
Evaluating 87/200...
Evaluating 88/200...
Evaluating 89/200...
Evaluating 90/200...
Evaluating 91/200...
Evaluating 92/200...
Evaluating 93/200...
Evaluating 94/200...
Evaluating 95/200...
Evaluating 96/200...
Evaluating 97/200...
Evaluating 98/200...
Evaluating 99/200...
Evaluating 100/200...
Evaluating 101/200...
Evaluating 102/200...
Evaluating 103/200...
Evaluating 104/200...
Evaluating 105/200...
Evaluating 106/200...
Evaluating 107/200...
Evaluating 108/200...
Evaluating 109/200...
Evaluating 110/200...
Evaluating 111/200...
Evaluating 112/200...
Evaluating 113/200...
Evaluating 114/200...
Evaluating 115/200...
Evaluating 116/200...
Evaluating 117/200...
Evaluating 118/200...
Evaluating 119/200...
Evaluating 120/200...
Evaluating 121/200...
Evaluating 122/200...
Evaluating 123/200...
Evaluating 124/200...
Evaluating 125/200...
Evaluating 126/200...
Evaluating 127/200...
Evaluating 128/200...
Evaluating 129/200...
Evaluating 130/200...
Evaluating 131/200...
Evaluating 132/200...
Evaluating 133/200...
Evaluating 134/200...
Evaluating 135/200...
Evaluating 136/200...
Evaluating 137/200...
Evaluating 138/200...
Evaluating 139/200...
Evaluating 140/200...
Evaluating 141/200...
Evaluating 142/200...
Evaluating 143/200...
Evaluating 144/200...
Evaluating 145/200...
Evaluating 146/200...
Evaluating 147/200...
Evaluating 148/200...
Evaluating 149/200...
Evaluating 150/200...
Evaluating 151/200...
Evaluating 152/200...
Evaluating 153/200...
Evaluating 154/200...
Evaluating 155/200...
Evaluating 156/200...
Evaluating 157/200...
Evaluating 158/200...
Evaluating 159/200...
Evaluating 160/200...
Evaluating 161/200...
Evaluating 162/200...
Evaluating 163/200...
Evaluating 164/200...
Evaluating 165/200...
Evaluating 166/200...
Evaluating 167/200...
Evaluating 168/200...
Evaluating 169/200...
Evaluating 170/200...
Evaluating 171/200...
Evaluating 172/200...
Evaluating 173/200...
Evaluating 174/200...
Evaluating 175/200...
Evaluating 176/200...
Evaluating 177/200...
Evaluating 178/200...
Evaluating 179/200...
Evaluating 180/200...
Evaluating 181/200...
Evaluating 182/200...
Evaluating 183/200...
Evaluating 184/200...
Evaluating 185/200...
Evaluating 186/200...
Evaluating 187/200...
Evaluating 188/200...
Evaluating 189/200...
Evaluating 190/200...
Evaluating 191/200...
Evaluating 192/200...
Evaluating 193/200...
Evaluating 194/200...
Evaluating 195/200...
Evaluating 196/200...
Evaluating 197/200...
Evaluating 198/200...
Evaluating 199/200...
Evaluating 200/200...
Average BLEU score : 0.001763
Average ROUGE score : 0.104920
Average BERT score : 0.829474

# TODO

- Augmenter l'epoch
- max_length=128 ou 256

## Hugging face Transformer (AventIQ)

https://huggingface.co/AventIQ-AI/gpt-2-movie-script-writter

In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM


# Load the tokenizer and model from Hugging Face (GPT2)
model_name = "AventIQ-AI/gpt-2-movie-script-writter"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained(model_name)

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [5]:
# Tokenize the dataset
def tokenize_function(example):
    encoding = tokenizer(example["Script"], truncation=True, padding="longest", max_length=256)
    encoding["labels"] = encoding["input_ids"].copy()
    return encoding

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["Script"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

Map: 100%|██████████| 800/800 [00:35<00:00, 22.51 examples/s]
Map: 100%|██████████| 200/200 [00:08<00:00, 22.23 examples/s]

### Train

In [6]:
# Train the model (Arguments)
training_args = TrainingArguments(
    output_dir="./aventiq-script",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    weight_decay=0.01,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=5,
    logging_dir="./logs",
    save_strategy="no",
    fp16=True,
    lr_scheduler_type="linear",
    warmup_steps=100,
)

In [7]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

In [8]:
# Train the model
trainer.train()

# Save the model
trainer.save_model("./aventiq-script")

In [9]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import evaluate

# Load the model for evaluation
model = GPT2LMHeadModel.from_pretrained("./aventiq-script")
tokenizer = GPT2Tokenizer.from_pretrained("./aventiq-script")

# Generate text
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")

def generate_text(prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

### Evaluation

In [10]:
bleu_scores = []
rouge_scores = []
bert_scores = []

PROMPT_LENGTH = 200
GENERATION_MAX_LENGTH = 100

total = len(test_texts)
i = 1

print("Evaluating the model on the test set...")
for full_text in test_texts:
    print(f"Evaluating {i}/{total}...")
    prompt = full_text[:PROMPT_LENGTH]
    reference = full_text[PROMPT_LENGTH:PROMPT_LENGTH + GENERATION_MAX_LENGTH]

    generated = generate_text(prompt, max_new_tokens=GENERATION_MAX_LENGTH)
    generated = generated[PROMPT_LENGTH:PROMPT_LENGTH + GENERATION_MAX_LENGTH]

    # BLEU
    bleu_result = bleu.compute(predictions=[generated], references=[[reference]])
    bleu_scores.append(bleu_result["bleu"])

    # ROUGE
    rouge_result = rouge.compute(predictions=[generated], references=[reference])
    rouge_scores.append(rouge_result["rougeL"])

    # BERTScore
    bert_result = bertscore.compute(predictions=[generated], references=[reference], lang="en")
    bert_scores.append(bert_result["f1"][0])

    i += 1

print(f"Average BLEU score : {sum(bleu_scores) / len(bleu_scores):.6f}")
print(f"Average ROUGE score : {sum(rouge_scores) / len(rouge_scores):.6f}")
print(f"Average BERT score : {sum(bert_scores) / len(bert_scores):.6f}")

Evaluating the model on the test set...
Evaluating 1/200...

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Evaluating 2/200...
Evaluating 3/200...
Evaluating 4/200...
Evaluating 5/200...
Evaluating 6/200...
Evaluating 7/200...
Evaluating 8/200...
Evaluating 9/200...
Evaluating 10/200...
Evaluating 11/200...
Evaluating 12/200...
Evaluating 13/200...
Evaluating 14/200...
Evaluating 15/200...
Evaluating 16/200...
Evaluating 17/200...
Evaluating 18/200...
Evaluating 19/200...
Evaluating 20/200...
Evaluating 21/200...
Evaluating 22/200...
Evaluating 23/200...
Evaluating 24/200...
Evaluating 25/200...
Evaluating 26/200...
Evaluating 27/200...
Evaluating 28/200...
Evaluating 29/200...
Evaluating 30/200...
Evaluating 31/200...
Evaluating 32/200...
Evaluating 33/200...
Evaluating 34/200...
Evaluating 35/200...
Evaluating 36/200...
Evaluating 37/200...
Evaluating 38/200...
Evaluating 39/200...
Evaluating 40/200...
Evaluating 41/200...
Evaluating 42/200...
Evaluating 43/200...
Evaluating 44/200...
Evaluating 45/200...
Evaluating 46/200...
Evaluating 47/200...
Evaluating 48/200...
Evaluating 49/200...
Evaluating 50/200...
Evaluating 51/200...
Evaluating 52/200...
Evaluating 53/200...
Evaluating 54/200...
Evaluating 55/200...
Evaluating 56/200...
Evaluating 57/200...
Evaluating 58/200...
Evaluating 59/200...
Evaluating 60/200...
Evaluating 61/200...
Evaluating 62/200...
Evaluating 63/200...
Evaluating 64/200...
Evaluating 65/200...
Evaluating 66/200...
Evaluating 67/200...
Evaluating 68/200...
Evaluating 69/200...
Evaluating 70/200...
Evaluating 71/200...
Evaluating 72/200...
Evaluating 73/200...
Evaluating 74/200...
Evaluating 75/200...
Evaluating 76/200...
Evaluating 77/200...
Evaluating 78/200...
Evaluating 79/200...
Evaluating 80/200...
Evaluating 81/200...
Evaluating 82/200...
Evaluating 83/200...
Evaluating 84/200...
Evaluating 85/200...
Evaluating 86/200...
Evaluating 87/200...
Evaluating 88/200...
Evaluating 89/200...
Evaluating 90/200...
Evaluating 91/200...
Evaluating 92/200...
Evaluating 93/200...
Evaluating 94/200...
Evaluating 95/200...
Evaluating 96/200...
Evaluating 97/200...
Evaluating 98/200...
Evaluating 99/200...
Evaluating 100/200...
Evaluating 101/200...
Evaluating 102/200...
Evaluating 103/200...
Evaluating 104/200...
Evaluating 105/200...
Evaluating 106/200...
Evaluating 107/200...
Evaluating 108/200...
Evaluating 109/200...
Evaluating 110/200...
Evaluating 111/200...
Evaluating 112/200...
Evaluating 113/200...
Evaluating 114/200...
Evaluating 115/200...
Evaluating 116/200...
Evaluating 117/200...
Evaluating 118/200...
Evaluating 119/200...
Evaluating 120/200...
Evaluating 121/200...
Evaluating 122/200...
Evaluating 123/200...
Evaluating 124/200...
Evaluating 125/200...
Evaluating 126/200...
Evaluating 127/200...
Evaluating 128/200...
Evaluating 129/200...
Evaluating 130/200...
Evaluating 131/200...
Evaluating 132/200...
Evaluating 133/200...
Evaluating 134/200...
Evaluating 135/200...
Evaluating 136/200...
Evaluating 137/200...
Evaluating 138/200...
Evaluating 139/200...
Evaluating 140/200...
Evaluating 141/200...
Evaluating 142/200...
Evaluating 143/200...
Evaluating 144/200...
Evaluating 145/200...
Evaluating 146/200...
Evaluating 147/200...
Evaluating 148/200...
Evaluating 149/200...
Evaluating 150/200...
Evaluating 151/200...
Evaluating 152/200...
Evaluating 153/200...
Evaluating 154/200...
Evaluating 155/200...
Evaluating 156/200...
Evaluating 157/200...
Evaluating 158/200...
Evaluating 159/200...
Evaluating 160/200...
Evaluating 161/200...
Evaluating 162/200...
Evaluating 163/200...
Evaluating 164/200...
Evaluating 165/200...
Evaluating 166/200...
Evaluating 167/200...
Evaluating 168/200...
Evaluating 169/200...
Evaluating 170/200...
Evaluating 171/200...
Evaluating 172/200...
Evaluating 173/200...
Evaluating 174/200...
Evaluating 175/200...
Evaluating 176/200...
Evaluating 177/200...
Evaluating 178/200...
Evaluating 179/200...
Evaluating 180/200...
Evaluating 181/200...
Evaluating 182/200...
Evaluating 183/200...
Evaluating 184/200...
Evaluating 185/200...
Evaluating 186/200...
Evaluating 187/200...
Evaluating 188/200...
Evaluating 189/200...
Evaluating 190/200...
Evaluating 191/200...
Evaluating 192/200...
Evaluating 193/200...
Evaluating 194/200...
Evaluating 195/200...
Evaluating 196/200...
Evaluating 197/200...
Evaluating 198/200...
Evaluating 199/200...
Evaluating 200/200...
Average BLEU score : 0.004729
Average ROUGE score : 0.106270
Average BERT score : 0.829400

## Hugging face Transformer (DistilGPT2)

https://huggingface.co/yroshan/moviescript

In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "yroshan/moviescript"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(model_name)

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

In [5]:
# Tokenize the dataset
def tokenize_function(example):
    encoding = tokenizer(example["Script"], truncation=True, padding="longest", max_length=256)
    encoding["labels"] = encoding["input_ids"].copy()
    return encoding

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["Script"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

Map: 100%|██████████| 800/800 [00:05<00:00, 141.40 examples/s]
Map: 100%|██████████| 200/200 [00:01<00:00, 144.35 examples/s]

In [14]:
# Train the model (Arguments)
training_args = TrainingArguments(
    output_dir="./distil-gpt2-script",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    weight_decay=0.01,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=5,
    logging_dir="./logs",
    save_strategy="no",
    fp16=True,
    lr_scheduler_type="linear",
    warmup_steps=100,
)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [15]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

In [16]:
# Train the model
trainer.train()

# Save the model
trainer.save_model("./distil-gpt2-script")

In [6]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import evaluate

# Load the model for evaluation
model = GPT2LMHeadModel.from_pretrained("./distil-gpt2-script")
tokenizer = GPT2Tokenizer.from_pretrained("./distil-gpt2-script")

# Generate text
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")

def generate_text(prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [7]:
bleu_scores = []
rouge_scores = []
bert_scores = []

PROMPT_LENGTH = 200
GENERATION_MAX_LENGTH = 100

total = len(test_texts)
i = 1

print("Evaluating the model on the test set...")
for full_text in test_texts:
    print(f"Evaluating {i}/{total}...")
    prompt = full_text[:PROMPT_LENGTH]
    reference = full_text[PROMPT_LENGTH:PROMPT_LENGTH + GENERATION_MAX_LENGTH]

    generated = generate_text(prompt, max_new_tokens=GENERATION_MAX_LENGTH)
    generated = generated[PROMPT_LENGTH:PROMPT_LENGTH + GENERATION_MAX_LENGTH]

    # BLEU
    bleu_result = bleu.compute(predictions=[generated], references=[[reference]])
    bleu_scores.append(bleu_result["bleu"])

    # ROUGE
    rouge_result = rouge.compute(predictions=[generated], references=[reference])
    rouge_scores.append(rouge_result["rougeL"])

    # BERTScore
    bert_result = bertscore.compute(predictions=[generated], references=[reference], lang="en")
    bert_scores.append(bert_result["f1"][0])

    i += 1

print(f"Average BLEU score : {sum(bleu_scores) / len(bleu_scores):.6f}")
print(f"Average ROUGE score : {sum(rouge_scores) / len(rouge_scores):.6f}")
print(f"Average BERT score : {sum(bert_scores) / len(bert_scores):.6f}")

Evaluating the model on the test set...
Evaluating 1/200...

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Evaluating 2/200...
Evaluating 3/200...
Evaluating 4/200...
Evaluating 5/200...
Evaluating 6/200...
Evaluating 7/200...
Evaluating 8/200...
Evaluating 9/200...
Evaluating 10/200...
Evaluating 11/200...
Evaluating 12/200...
Evaluating 13/200...
Evaluating 14/200...
Evaluating 15/200...
Evaluating 16/200...
Evaluating 17/200...
Evaluating 18/200...
Evaluating 19/200...
Evaluating 20/200...
Evaluating 21/200...
Evaluating 22/200...
Evaluating 23/200...
Evaluating 24/200...
Evaluating 25/200...
Evaluating 26/200...
Evaluating 27/200...
Evaluating 28/200...
Evaluating 29/200...
Evaluating 30/200...
Evaluating 31/200...
Evaluating 32/200...
Evaluating 33/200...
Evaluating 34/200...
Evaluating 35/200...
Evaluating 36/200...
Evaluating 37/200...
Evaluating 38/200...
Evaluating 39/200...
Evaluating 40/200...
Evaluating 41/200...
Evaluating 42/200...
Evaluating 43/200...
Evaluating 44/200...
Evaluating 45/200...
Evaluating 46/200...
Evaluating 47/200...
Evaluating 48/200...
Evaluating 49/200...
Evaluating 50/200...
Evaluating 51/200...
Evaluating 52/200...
Evaluating 53/200...
Evaluating 54/200...
Evaluating 55/200...
Evaluating 56/200...
Evaluating 57/200...
Evaluating 58/200...
Evaluating 59/200...
Evaluating 60/200...
Evaluating 61/200...
Evaluating 62/200...
Evaluating 63/200...
Evaluating 64/200...
Evaluating 65/200...
Evaluating 66/200...
Evaluating 67/200...
Evaluating 68/200...
Evaluating 69/200...
Evaluating 70/200...
Evaluating 71/200...
Evaluating 72/200...
Evaluating 73/200...
Evaluating 74/200...
Evaluating 75/200...
Evaluating 76/200...
Evaluating 77/200...
Evaluating 78/200...
Evaluating 79/200...
Evaluating 80/200...
Evaluating 81/200...
Evaluating 82/200...
Evaluating 83/200...
Evaluating 84/200...
Evaluating 85/200...
Evaluating 86/200...
Evaluating 87/200...
Evaluating 88/200...
Evaluating 89/200...
Evaluating 90/200...
Evaluating 91/200...
Evaluating 92/200...
Evaluating 93/200...
Evaluating 94/200...
Evaluating 95/200...
Evaluating 96/200...
Evaluating 97/200...
Evaluating 98/200...
Evaluating 99/200...
Evaluating 100/200...
Evaluating 101/200...
Evaluating 102/200...
Evaluating 103/200...
Evaluating 104/200...
Evaluating 105/200...
Evaluating 106/200...
Evaluating 107/200...
Evaluating 108/200...
Evaluating 109/200...
Evaluating 110/200...
Evaluating 111/200...
Evaluating 112/200...
Evaluating 113/200...
Evaluating 114/200...
Evaluating 115/200...
Evaluating 116/200...
Evaluating 117/200...
Evaluating 118/200...
Evaluating 119/200...
Evaluating 120/200...
Evaluating 121/200...
Evaluating 122/200...
Evaluating 123/200...
Evaluating 124/200...
Evaluating 125/200...
Evaluating 126/200...
Evaluating 127/200...
Evaluating 128/200...
Evaluating 129/200...
Evaluating 130/200...
Evaluating 131/200...
Evaluating 132/200...
Evaluating 133/200...
Evaluating 134/200...
Evaluating 135/200...
Evaluating 136/200...
Evaluating 137/200...
Evaluating 138/200...
Evaluating 139/200...
Evaluating 140/200...
Evaluating 141/200...
Evaluating 142/200...
Evaluating 143/200...
Evaluating 144/200...
Evaluating 145/200...
Evaluating 146/200...
Evaluating 147/200...
Evaluating 148/200...
Evaluating 149/200...
Evaluating 150/200...
Evaluating 151/200...
Evaluating 152/200...
Evaluating 153/200...
Evaluating 154/200...
Evaluating 155/200...
Evaluating 156/200...
Evaluating 157/200...
Evaluating 158/200...
Evaluating 159/200...
Evaluating 160/200...
Evaluating 161/200...
Evaluating 162/200...
Evaluating 163/200...
Evaluating 164/200...
Evaluating 165/200...
Evaluating 166/200...
Evaluating 167/200...
Evaluating 168/200...
Evaluating 169/200...
Evaluating 170/200...
Evaluating 171/200...
Evaluating 172/200...
Evaluating 173/200...
Evaluating 174/200...
Evaluating 175/200...
Evaluating 176/200...
Evaluating 177/200...
Evaluating 178/200...
Evaluating 179/200...
Evaluating 180/200...
Evaluating 181/200...
Evaluating 182/200...
Evaluating 183/200...
Evaluating 184/200...
Evaluating 185/200...
Evaluating 186/200...
Evaluating 187/200...
Evaluating 188/200...
Evaluating 189/200...
Evaluating 190/200...
Evaluating 191/200...
Evaluating 192/200...
Evaluating 193/200...
Evaluating 194/200...
Evaluating 195/200...
Evaluating 196/200...
Evaluating 197/200...
Evaluating 198/200...
Evaluating 199/200...
Evaluating 200/200...
Average BLEU score : 0.003305
Average ROUGE score : 0.097206
Average BERT score : 0.827883